# Site settings
title:          Alex Le
description:    "Alex Le's Blog"
url:            "https://alexle.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Alex Le 
  url:          https://alexanderle.com
  email:        alex.csm@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:title
paginate:       7 

# Excludes
exclude:        [Gemfile, Gemfile.lock, tale.gemspec, vendor]
